### ISSUE TITLE
improve the ui of website

### ISSUE THREAD

**Issue by sonal3yadav** [sonal3yadav/Calculator#2]
improve the user interface of whole website which looks good to user

**Comment by 21omkarsase** [comment]
Hey @sonal3yadav , I would like to work on it.
Can you assign this to me.

**Comment by GitArya27** [comment]
I would like to work on this issue please assign this issue to me

**Comment by sonal3yadav** [comment]
I have assigned you the issue. @21omkarsase

**Comment by sonal3yadav** [comment]
I have assigned you the issue. @GitArya27

**Comment by thisisamish** [comment]
Hey @sonal3yadav! Can you please deploy the website on Netlify or GitHub pages so it is easier to see the website?

**Comment by sonal3yadav** [comment]
@thisisamish I will update my readme file,which will definitely help u.
