### ISSUE TITLE
add C button

### ISSUE THREAD

**Issue by sonal3yadav** [sonal3yadav/Calculator#4]
Add c button and provide functionality to it.After clicking the C button the result should get cleared.

**Comment by Premjeet1804** [comment]
!assign me please i will try that

**Comment by sanusisusi** [comment]
hello! how can i contribute to this project

**Comment by mekasandhyagouri** [comment]
Assign this to me! I would love to work on this issue

**Comment by ankitkumar0622** [comment]
Hi, can you assign this task to me.

**Comment by sonal3yadav** [comment]
I have assigned you the issue. @ankitkumar0622
