### ISSUE TITLE
update readme by giving brief description about calculator and its buttons

### ISSUE THREAD

**Issue by sonal3yadav** [sonal3yadav/Calculator#9]

**Comment by aman6969** [comment]
please assign this to me @sonal3yadav

**Comment by SarveshPatil29** [comment]
Hi! I would like to work on this issue. Can you please assign it to me? @sonal3yadav

**Comment by sonal3yadav** [comment]
assigned @aman6969  @SarveshPatil29

**Comment by stutimongia2024** [comment]
@sonal3yadav the readme file requires description of the project. I can add the same. Please assign me this issue.
